# Generated by Django 4.1.5 on 2023-02-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksweb', '0002_alter_book_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
