# Generated by Django 4.1.5 on 2023-02-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksweb', '0005_author_foto_alter_author_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='foto',
        ),
        migrations.AddField(
            model_name='author',
            name='foto_author',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото'),
        ),
    ]
